const CATEGORIES = [
  'INGÉNIERIE LOGICIELLE',
  'DÉVELOPPEMENT PERSONNEL',
  'STARTUP',
  'CONNAISSANCES TRANSVERSALES'
];

const FORMATS = ['VIDEO', 'LIVRE'];

module.exports = { CATEGORIES, FORMATS };
